version: '3.8'

services:
  ip-scanner:
    image: davidyannick/ip-scanner:linux-amd64
    container_name: ip-scanner-production
    network_mode: host
    restart: unless-stopped
    
    environment:
      - TZ=Europe/Paris
    
    cap_add:
      - NET_ADMIN
      - NET_RAW
    
    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 60s
      timeout: 5s
      retries: 2
    
    # Logging
    logging:
      options:
        max-size: "10m"
        max-file: "2"
