version: '3.8'

services:
  ip-scanner:
    image: davidyannick/ip-scanner:linux-amd64
    container_name: ip-scanner
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    cap_add:
      - NET_ADMIN
      - NET_RAW
